---
- name: Install DNS server package
  yum: name=bind state=present

- name: Copy named.conf
  template: src=named.conf.j2 dest=/etc/named.conf

- name: Create example.com zone
  template: src=example.com.db.j2 dest=/var/named/dynamic/{{ ose_domain }}.db

- name: Create xpaasqe.redhat.com zone
  template: src=xpaasqe.redhat.com.db.j2 dest=/var/named/dynamic/xpaasqe.redhat.com.db

- name: Start and enable named service
  service: name=named enabled=yes state=started

- name: Install iptables packages
  yum: name=iptables-services state=present

- name: Open port TCP 53
  lineinfile: dest=/etc/sysconfig/iptables state=present
              insertafter="-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT"
              line="-A INPUT -p tcp -m state --state NEW -m tcp --dport 53 -j ACCEPT"

- name: Open port UDP 53
  lineinfile: dest=/etc/sysconfig/iptables state=present
              insertafter="-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT"
              line="-A INPUT -p udp -m state --state NEW -m udp --dport 53 -j ACCEPT"

- name: Restart iptables service
  service: name=iptables state=restarted