---
- name: Add routing config to master config
  lineinfile: dest=/etc/origin/master/master-config.yaml line='routingConfig{{":"}}'
  register: result

- name: Restart master service
  service: name=atomic-openshift-master state=restarted
  when: result.changed
