# change this according to system you are using
# beaker
#ansible_ssh_user: root
# OpenStack
ansible_ssh_user: cloud-user

ansible_ssh_private_key_file: /Users/luigizuccarelli/.ssh/osev31.pem

# true: install released (GA) OSE3 version from the official channel
# false: install latest (pre-released) OSE3 version from puddle
install_released_ose: false

# true: use Docker registry with released images (ie. registry.access.redhat.com)
# false: use pre-release Docker registry
use_released_registry: false

ose_domain: ose3-os1public-01.feedhenry.io
ose_apps: cloudapps

ose_installer_uri: https://github.com/openshift/openshift-ansible.git
ose_installer_branch: master
