---
- hosts: inventory
  sudo: yes
  roles:
    - hostname-setup
    - registration
    - system-users
    - prepare-systems

- hosts: dns
  sudo: yes
  roles:
    - dns-setup

- hosts: inventory
  sudo: yes
  roles:
    - dhcp-setup

- hosts: 127.0.0.1
  sudo: no
  roles:
    - installer

- hosts: node
  sudo: yes
  roles:
    - docker-setup

- hosts: master
  sudo: yes
  roles:
    - setup-master
    - ose-users
    - deploy-security-resources
    - deploy-services
#    - install-xpaas-resources
