---
#- name: Install Docker package
#  yum: name=docker state=present

- name: Configure Docker to allow insecure-registry=0.0.0.0/0
  replace: dest='/etc/sysconfig/docker'
           regexp="--insecure-registry=\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}/\d{1,2}"
           replace="--insecure-registry=0.0.0.0/0"

- name: Restart Docker service
  service: name=docker state=restarted