---
- name: List images
  command: oc get -n openshift is
  register: images

- name: Install xpaas images
  command: oc create -n openshift -f https://raw.githubusercontent.com/jboss-openshift/application-templates/master/jboss-image-streams.json
  when: images.stdout.find("jboss-eap6-openshift") == -1

- name: List templates
  command: oc get -n openshift template
  register: templates

- name: Install xPaaS templates
  command: oc create -n openshift -f {{ item.url }}
  when: templates.stdout.find("{{ item.name }}") == -1
  with_items:
    - { name: 'eap6-basic-sti', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/eap/eap6-basic-sti.json'}
    - { name: 'eap6-amq-sti', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/eap/eap6-amq-sti.json'}
    - { name: 'eap6-amq-persistent-sti', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/eap/eap6-amq-persistent-sti.json'}
    - { name: 'eap6-mongodb-persistent-sti', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/eap/eap6-mongodb-persistent-sti.json'}
    - { name: 'eap6-mongodb-sti', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/eap/eap6-mongodb-sti.json'}
    - { name: 'eap6-mysql-persistent-sti', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/eap/eap6-mysql-persistent-sti.json'}
    - { name: 'eap6-mysql-sti', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/eap/eap6-mysql-sti.json'}
    - { name: 'eap6-postgresql-persistent-sti', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/eap/eap6-postgresql-persistent-sti.json'}
    - { name: 'eap6-postgresql-sti', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/eap/eap6-postgresql-sti.json'}
    - { name: 'jws-tomcat7-basic-sti', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/webserver/jws-tomcat7-basic-sti.json'}
    - { name: 'jws-tomcat7-mongodb-persistent-sti', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/webserver/jws-tomcat7-mongodb-persistent-sti.json'}
    - { name: 'jws-tomcat7-mongodb-sti', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/webserver/jws-tomcat7-mongodb-sti.json'}
    - { name: 'jws-tomcat7-mysql-sti', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/webserver/jws-tomcat7-mysql-sti.json'}
    - { name: 'jws-tomcat7-postgresql-persistent-sti', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/webserver/jws-tomcat7-postgresql-persistent-sti.json'}
    - { name: 'jws-tomcat7-postgresql-sti', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/webserver/jws-tomcat7-postgresql-sti.json'}
    - { name: 'jws-tomcat8-basic-sti', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/webserver/jws-tomcat8-basic-sti.json'}
    - { name: 'jws-tomcat8-mongodb-persistent-sti', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/webserver/jws-tomcat8-mongodb-persistent-sti.json'}
    - { name: 'jws-tomcat8-mongodb-sti', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/webserver/jws-tomcat8-mongodb-sti.json'}
    - { name: 'jws-tomcat8-mysql-persistent-sti', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/webserver/jws-tomcat8-mysql-persistent-sti.json'}
    - { name: 'jws-tomcat8-mysql-sti', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/webserver/jws-tomcat8-mysql-sti.json'}
    - { name: 'jws-tomcat8-postgresql-persistent-sti', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/webserver/jws-tomcat8-postgresql-persistent-sti.json'}
    - { name: 'jws-tomcat8-postgresql-sti', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/webserver/jws-tomcat8-postgresql-sti.json'}
    - { name: 'amq6', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/amq/amq6.json'}
    - { name: 'amq6-persistent', url: 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/amq/amq6-persistent.json'}
