---
- name: Find Service Accounts
  command: oc get serviceAccount -n default
  register: sa

- name: Copy authorized_keys file
  copy: src=router-sa.json dest=/tmp/router-sa.json
  when: sa.stdout.find("router") == -1

- name: Create 'router' Service Account
  command: oc create -f /tmp/router-sa.json
  when: sa.stdout.find("router") == -1

- name: Find Security Context Constraints
  command: oc get scc -n default
  register: scc

- name: Create 'hostport' Security Context Constraint
  command:  oc create -f https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/authorization/scc/scc_hostport.yaml
  when: scc.stdout.find("hostport") == -1

