---
- name: Allow scheduling pods on master
  command: oadm manage-node {{ ose_hostname }}.{{ ose_domain }} --schedulable

- name: Find services
  command: oc get services -n default
  register: services

- name: Deploy router
  command: oadm router --credentials=/etc/openshift/master/openshift-router.kubeconfig --images='rcm-img-docker01.build.eng.bos.redhat.com:5001/openshift3/ose-${component}:${version}' --selector='region=infra' --service-account='router'
  when: services.stdout.find("router") == -1

- name: Deploy docker registry
  command: oadm registry --credentials=/etc/openshift/master/openshift-registry.kubeconfig --images='rcm-img-docker01.build.eng.bos.redhat.com:5001/openshift3/ose-${component}:${version}' --selector='region=infra'
  when: services.stdout.find("docker-registry") == -1